[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@api3/contracts=lib/contracts/contracts", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@api3/airnode-protocol=lib/airnode/packages/airnode-protocol", "@api3/airnode-protocol-v1=lib/airnode-protocol-v1", "@api3/airnode-protocol=lib/airnode/packages/airnode-protocol", "@wormhole-solidity-sdk/src=lib/wormhole-solidity-sdk", "@wormhole/contracts=lib/wormhole/ethereum/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
